package com.smilecare.dao;

import com.smilecare.db.DbConnection;
import com.smilecare.model.Appointment;
import com.smilecare.model.Bill;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Optional;

public class BillDao {

    private static final String JOINED =
        "SELECT b.bill_no, b.treatment_cost, b.consultation_fee, b.total, b.pricing_strategy, b.issued_at, " +
        "       a.appointment_no, p.name AS p_name, d.name AS d_name, t.treatment_type " +
        "FROM bills b " +
        "JOIN appointments a ON a.id = b.appointment_id " +
        "JOIN patients   p ON p.id = a.patient_id " +
        "JOIN dentists   d ON d.id = a.dentist_id " +
        "JOIN treatments t ON t.id = a.treatment_id ";

    public Optional<Bill> findByAppointmentNo(String appointmentNo) throws SQLException {
        try (Connection c = DbConnection.get().open();
             PreparedStatement ps = c.prepareStatement(JOINED + "WHERE a.appointment_no = ?")) {
            ps.setString(1, appointmentNo);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(map(rs)) : Optional.empty();
            }
        }
    }

    /** BIL-7101, BIL-7102 and so on. */
    public String nextNumber() throws SQLException {
        String sql = "SELECT IFNULL(MAX(CAST(SUBSTRING(bill_no, 5) AS UNSIGNED)), 7100) FROM bills";
        try (Connection c = DbConnection.get().open();
             PreparedStatement ps = c.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return "BIL-" + (rs.getLong(1) + 1);
        }
    }

    /**
     * Writes the receipt and completes the appointment in one transaction, so
     * a crash halfway through can never leave a paid visit marked as pending.
     * The total column is generated by MySQL from the two amounts.
     */
    public Bill insertAndComplete(Appointment appt, String billNo,
                                  BigDecimal treatmentCost, BigDecimal consultationFee,
                                  String pricingStrategy, Integer issuedBy) throws SQLException {

        String insert = "INSERT INTO bills " +
                        "(bill_no, appointment_id, treatment_cost, consultation_fee, pricing_strategy, issued_by) " +
                        "VALUES (?, ?, ?, ?, ?, ?)";
        String complete = "UPDATE appointments SET status = 'Completed' WHERE id = ?";

        try (Connection c = DbConnection.get().open()) {
            c.setAutoCommit(false);
            try (PreparedStatement ps = c.prepareStatement(insert);
                 PreparedStatement up = c.prepareStatement(complete)) {

                ps.setString(1, billNo);
                ps.setInt(2, appt.id());
                ps.setBigDecimal(3, treatmentCost);
                ps.setBigDecimal(4, consultationFee);
                ps.setString(5, pricingStrategy);
                if (issuedBy == null) {
                    ps.setNull(6, java.sql.Types.INTEGER);
                } else {
                    ps.setInt(6, issuedBy);
                }
                ps.executeUpdate();

                up.setInt(1, appt.id());
                up.executeUpdate();

                c.commit();
            } catch (SQLException e) {
                c.rollback();
                throw e;
            } finally {
                c.setAutoCommit(true);
            }
        }

        return findByAppointmentNo(appt.appointmentNo())
            .orElseThrow(() -> new SQLException("The bill was written but could not be read back."));
    }

    private static Bill map(ResultSet rs) throws SQLException {
        return new Bill(
            rs.getString("bill_no"),
            rs.getString("appointment_no"),
            rs.getString("p_name"),
            rs.getString("d_name"),
            rs.getString("treatment_type"),
            rs.getBigDecimal("treatment_cost"),
            rs.getBigDecimal("consultation_fee"),
            rs.getBigDecimal("total"),
            rs.getString("pricing_strategy"),
            rs.getTimestamp("issued_at").toLocalDateTime());
    }
}
